version: '3.7'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '35729:35729' # warm reloading for react create app
    environment:
      - NODE_ENV=development
    depends_on:
      - server
      - redis

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app/
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=spoonacular
