version: '3.7'

services:
  spoonacular:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  redis:
    image: redis:latest
    ports:
      - "6379:6379"